<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_packageListFrame</name>
   <tag></tag>
   <elementGuidId>15b002ec-dcbc-4bdd-9cb2-448ba55cbc6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='packageListFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;packageListFrame&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>91dd1d4e-2644-4e62-96d9-de71e9f9e64b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>overview-frame.html</value>
      <webElementGuid>7b19ecb2-bc82-4ad7-aab4-dee746cc5c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>packageListFrame</value>
      <webElementGuid>f13e479b-52bb-4bd9-b52b-e1c2ec6823cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>All Packages</value>
      <webElementGuid>d6273619-07f0-4324-a1ca-c54dabba6501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;mainContainer&quot;]/div[@class=&quot;leftContainer&quot;]/div[@class=&quot;leftTop&quot;]/iframe[1]</value>
      <webElementGuid>f0be3a37-10e8-4bc8-aea3-0e0897a8256d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='packageListFrame']</value>
      <webElementGuid>f7a72208-7787-438f-af91-63864cd4f144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>a223cbc5-e5a5-45e7-8097-25f2778c2d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'overview-frame.html' and @name = 'packageListFrame' and @title = 'All Packages']</value>
      <webElementGuid>172d578a-6566-49ec-8c10-c92442b70fef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
