<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_Time</name>
   <tag></tag>
   <elementGuidId>8cdfb87c-7aaa-4d1c-8f31-8492c9d752d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu_time_viewTimeModule > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='menu_time_viewTimeModule']/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>d20db375-c40e-440f-abbc-259900afe89e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Time</value>
      <webElementGuid>d4b88740-db55-45d5-a7e3-39f504796686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu_time_viewTimeModule&quot;)/b[1]</value>
      <webElementGuid>ba5c3641-1ba3-4290-9139-3170789bac01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menu_time_viewTimeModule']/b</value>
      <webElementGuid>eddbecf7-0e3b-4d90-8e8b-ce4fc8c7444c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assign Leave'])[1]/following::b[1]</value>
      <webElementGuid>da3aa265-9107-4df9-97dd-402e914a9ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leave List'])[1]/following::b[1]</value>
      <webElementGuid>c8dcbaee-0ce7-449b-a585-54bca016cd70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Timesheets'])[1]/preceding::b[1]</value>
      <webElementGuid>ac1ab142-6db3-47f9-9439-5e7089766292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee Timesheets'])[1]/preceding::b[1]</value>
      <webElementGuid>f38e9848-ace2-4ae4-b858-69d6fb2f8d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Time']/parent::*</value>
      <webElementGuid>d0d2a7dd-e74c-4ad9-ab36-55ba5594adf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/b</value>
      <webElementGuid>4b182071-e7d0-45eb-acb0-d82adb12f521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'Time' or . = 'Time')]</value>
      <webElementGuid>6c65f3df-90a1-4acf-9a16-c04a621659ac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
